#!/usr/bin/env zsh

if [ ! -d 'venv' ]; then
    echo "Creating virtual environment..."
    python3 -m venv venv > /dev/null
    source venv/bin/activate
    echo "Installing dependencies..."
    pip install -r requirements.txt > /dev/null
    echo "Done!"
else
    source venv/bin/activate
fi

python3 -m apple_photos_export "$@"
