// This file is NOT generated by Diesel CLI, but is written manually.
// This is done because we don't have any control over the schema of the database and only
// reverse-engineered the schema from the database file.

diesel::table! {
    #[sql_name = "ZGENERICALBUM"]
    albums (id) {
        #[sql_name = "Z_PK"]
        id -> Integer,

        #[sql_name = "ZKIND"]
        kind -> Integer,

        #[sql_name = "ZPARENTFOLDER"]
        parent_id -> Nullable<Integer>,

        #[sql_name = "ZTITLE"]
        name -> Nullable<VarChar>,

        #[sql_name = "ZSTARTDATE"]
        start_date -> Nullable<Float>,

        #[sql_name = "ZTRASHEDSTATE"]
        trashed -> Bool,
    }
}

diesel::table! {
    #[sql_name = "ZASSET"]
    assets (id) {
        #[sql_name = "Z_PK"]
        id -> Integer,

        #[sql_name = "ZUUID"]
        uuid -> VarChar,

        #[sql_name = "ZDIRECTORY"]
        dir -> VarChar,

        #[sql_name = "ZFILENAME"]
        filename -> VarChar,

        #[sql_name = "ZUNIFORMTYPEIDENTIFIER"]
        uniform_type_identifier -> VarChar,

        #[sql_name = "ZDATECREATED"]
        date -> Float,

        #[sql_name = "ZHIDDEN"]
        hidden -> Bool,

        #[sql_name = "ZFAVORITE"]
        favorite -> Bool,

        #[sql_name = "ZTRASHEDSTATE"]
        trashed -> Bool,

        #[sql_name = "ZVISIBILITYSTATE"]
        visibility_state -> Integer,

        #[sql_name = "ZCLOUDLOCALSTATE"]
        cloud_local_state -> Bool,

        #[sql_name = "ZDUPLICATEASSETVISIBILITYSTATE"]
        duplicate_asset_visibility_state -> Integer,

        #[sql_name = "ZHASADJUSTMENTS"]
        has_adjustments -> Bool,
    }
}

diesel::table! {
    #[sql_name = "ZADDITIONALASSETATTRIBUTES"]
    asset_attributes (id) {
        #[sql_name = "Z_PK"]
        id -> Integer,

        #[sql_name = "ZASSET"]
        asset_id -> Integer,

        #[sql_name = "ZORIGINALFILENAME"]
        original_filename -> VarChar,

        #[sql_name = "ZMASTERFINGERPRINT"]
        master_fingerprint -> VarChar,
    }
}

diesel::table! {
    #[sql_name = "ZINTERNALRESOURCE"]
    internal_resources (id) {
        #[sql_name = "Z_PK"]
        id -> Integer,

        #[sql_name = "ZFINGERPRINT"]
        fingerprint -> VarChar,

        #[sql_name = "ZLOCALAVAILABILITY"]
        local_availability -> Integer,

        #[sql_name = "ZCOMPACTUTI"]
        compact_uti -> Integer,
    }
}

diesel::table! {
    #[sql_name = "Z_28ASSETS"]
    album_assets (asset_id, album_id) {
        #[sql_name = "Z_3ASSETS"]
        asset_id -> Integer,

        #[sql_name = "Z_28ALBUMS"]
        album_id -> Integer,
    }
}

diesel::joinable!(asset_attributes -> assets (asset_id));
diesel::joinable!(album_assets -> assets (asset_id));
diesel::joinable!(album_assets -> albums (album_id));

diesel::allow_tables_to_appear_in_same_query!(
    albums,
    assets,
    asset_attributes,
    internal_resources,
    album_assets
);
